### ISSUE TITLE
About multi-scale test

### ISSUE THREAD

**Issue by ming71** [xhzdeng/stela#7]
As described in your paper, multi-scale test  on ICDAR2015 challenge4  raises F1 score  from 63.28% to **83.33%**. How can you concluded this amazing boost?

I've tried this trick on my model, only to find F1 score **dropped** from 62.16% to  60.27% (ICDAR challenge 4 ).What's wong with my  multi-scale testing?
My methd:
1. Obtain detections from random various scales(e,g 608 and 512),  which are generated via **preliminary** NMS (conf_thres=0.1, nms_thre=0.9 for speed) to reduce memory cost.
2. Concat these detections (from random various scales), and conduct **formal** NMS with conf_thres=0.5, nms_thres = 0.5.
Anything wrong with it?
thanks.

**Comment by xhzdeng** [comment]
I did not use multi-scale testing on ICDAR 2015. ^_^

**Comment by ming71** [comment]
> I did not use multi-scale testing on ICDAR 2015. ^_^

Sorry， It's my  misread. It's really a good work !

**Comment by ghost** [comment]
@ming71 kindly close this issue
